// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var Gatsby = require("gatsby");
var Settings$ReactTemplate = require("./Settings.bs.js");

var header = Css.style(/* :: */[
      Css.backgroundColor(Css.hex("223f63")),
      /* :: */[
        Css.marginBottom(Css.px(16)),
        /* [] */0
      ]
    ]);

var content = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.alignItems(/* center */98248149),
        /* :: */[
          Css.justifyContent(/* spaceBetween */516682146),
          /* :: */[
            Css.margin2(Css.px(0), /* auto */-1065951377),
            /* :: */[
              Css.maxWidth(Css.px(1000)),
              /* :: */[
                Css.padding2(Css.px(16), Css.px(24)),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

var h1 = Css.style(/* :: */[
      Css.margin(Css.px(0)),
      /* [] */0
    ]);

var link = Css.style(/* :: */[
      Css.color(Css.white),
      /* :: */[
        Css.textDecoration(Css.none),
        /* :: */[
          Css.marginLeft(/* `em */[
                22632,
                1.0
              ]),
          /* [] */0
        ]
      ]
    ]);

var headerLink = Css.style(/* :: */[
      Settings$ReactTemplate.Header.fontFamily,
      /* :: */[
        Css.color(Css.white),
        /* :: */[
          Css.textDecoration(Css.none),
          /* [] */0
        ]
      ]
    ]);

var nav = Css.style(/* [] */0);

var Styles = {
  header: header,
  content: content,
  h1: h1,
  link: link,
  headerLink: headerLink,
  nav: nav
};

function Header(Props) {
  var siteTitle = Props.siteTitle;
  return React.createElement("header", {
              className: header
            }, React.createElement("div", {
                  className: content
                }, React.createElement("h1", {
                      className: h1
                    }, React.createElement(Gatsby.Link, {
                          to: "/",
                          className: headerLink,
                          children: siteTitle
                        })), React.createElement("nav", {
                      className: nav
                    }, React.createElement(Gatsby.Link, {
                          to: "/team",
                          className: link,
                          children: "Team"
                        }), React.createElement(Gatsby.Link, {
                          to: "/projects",
                          className: link,
                          children: "Projects"
                        }), React.createElement(Gatsby.Link, {
                          to: "/blog",
                          className: link,
                          children: "Blog"
                        }))));
}

var make = Header;

var $$default = Header;

exports.Styles = Styles;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* header Not a pure module */
