// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");

function str(prim) {
  return prim;
}

function Index(Props) {
  return React.createElement("div", undefined, React.createElement("h1", {
                  className: Css.style(/* :: */[
                        Css.fontFamily("Merriweather"),
                        /* :: */[
                          Css.fontWeight(/* black */888264127),
                          /* :: */[
                            Css.color(Css.hex("223f63")),
                            /* [] */0
                          ]
                        ]
                      ])
                }, "Quantified Uncertainty Research Institute"), React.createElement("p", undefined, "We create advanced forecasting infrastructure to support globally-beneficial initiatives."));
}

var make = Index;

var $$default = Index;

exports.str = str;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* Css Not a pure module */
