// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");

function str(prim) {
  return prim;
}

function Projects(Props) {
  return React.createElement("div", undefined, React.createElement("h1", {
                  className: Css.style(/* :: */[
                        Css.fontFamily("Merriweather"),
                        /* :: */[
                          Css.fontWeight(/* black */888264127),
                          /* :: */[
                            Css.color(Css.hex("223f63")),
                            /* [] */0
                          ]
                        ]
                      ])
                }, "Team"), React.createElement("h2", undefined, "Foretold"), React.createElement("h2", undefined, "Ken (Alpha)"), React.createElement("h2", undefined, "DistPlus (Alpha)"), React.createElement("h2", undefined, "AI Forecasting Dictionary"));
}

var make = Projects;

var $$default = Projects;

exports.str = str;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* Css Not a pure module */
