// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Settings$ReactTemplate = require("./Settings.bs.js");

function str(prim) {
  return prim;
}

function Projects(Props) {
  return React.createElement("div", undefined, React.createElement("h1", {
                  className: Settings$ReactTemplate.Header.defaults
                }, "Projects"), React.createElement("div", undefined, React.createElement("strong", undefined, "Foretold"), React.createElement("p", undefined, "Foretold is a prediction tournament, similar to that discussed in Superforecasting."), React.createElement("a", {
                      href: "https://www.foretold.io/"
                    }, "Website"), React.createElement("a", {
                      href: "https://github.com/foretold-app/foretold"
                    }, "Github")), React.createElement("div", undefined, React.createElement("strong", undefined, "Ken (Alpha)"), React.createElement("a", {
                      href: "https://kenstandard.com/"
                    }, "Website"), React.createElement("a", {
                      href: "https://github.com/kenstandard/ken-js"
                    }, "Github")), React.createElement("div", undefined, React.createElement("strong", undefined, "DistPlus (Alpha)"), React.createElement("a", {
                      href: "https://github.com/foretold-app/estiband"
                    }, "Github")));
}

var make = Projects;

var $$default = Projects;

exports.str = str;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
