// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");

var color = Css.hex("223f63");

var fontFamily = Css.fontFamily("Merriweather");

var defaults = Css.style(/* :: */[
      Css.fontFamily("Merriweather"),
      /* :: */[
        Css.fontWeight(/* black */888264127),
        /* :: */[
          Css.color(Css.hex("223f63")),
          /* [] */0
        ]
      ]
    ]);

var Header = {
  color: color,
  fontFamily: fontFamily,
  defaults: defaults
};

exports.Header = Header;
/* color Not a pure module */
