// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Settings$ReactTemplate = require("./Settings.bs.js");

function str(prim) {
  return prim;
}

function Team(Props) {
  return React.createElement("div", undefined, React.createElement("h1", {
                  className: Settings$ReactTemplate.Header.defaults
                }, "Team"), React.createElement("h2", undefined, "Ben Goldhaber"), React.createElement("strong", undefined, "Project Lead"), React.createElement("p", undefined, "Text XYZ"), React.createElement("h2", undefined, "Ozzie Gooen"), React.createElement("strong", undefined, "Affiliated Researcher"), React.createElement("p", undefined, "Text XYZ"), React.createElement("h2", undefined, "Jacob Lagerros"), React.createElement("strong", undefined, "Affiliated Researcher"), React.createElement("p", undefined, "Text XYZ"));
}

var make = Team;

var $$default = Team;

exports.str = str;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
