// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");

function str(prim) {
  return prim;
}

function Team(Props) {
  return React.createElement("div", undefined, React.createElement("h1", {
                  className: Css.style(/* :: */[
                        Css.fontFamily("Merriweather"),
                        /* :: */[
                          Css.fontWeight(/* black */888264127),
                          /* :: */[
                            Css.color(Css.hex("223f63")),
                            /* [] */0
                          ]
                        ]
                      ])
                }, "Team"), React.createElement("h2", undefined, "Ben Goldhaber"), React.createElement("strong", undefined, "Project Lead"), React.createElement("p", undefined, "Text XYZ"), React.createElement("h2", undefined, "Ozzie Gooen"), React.createElement("strong", undefined, "Affiliated Researcher"), React.createElement("p", undefined, "Text XYZ"), React.createElement("h2", undefined, "Jacob Lagerros"), React.createElement("strong", undefined, "Affiliated Researcher"), React.createElement("p", undefined, "Text XYZ"));
}

var make = Team;

var $$default = Team;

exports.str = str;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* Css Not a pure module */
